# Generated by Django 5.2.10 on 2026-01-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_category_id_category_id_and_more'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='bookmark_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='videoprogress',
            old_name='progress_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='courses.lecture'),
        ),
    ]
