# Generated by Django 5.1.15 on 2026-02-02 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0002_add_unique_user_course_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['free', 'pending', 'paid', 'refunded', 'expired'])), name='valid_enrollment_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'authorized', 'captured', 'failed', 'refunded'])), name='valid_payment_status'),
        ),
    ]
