# Generated by Django 5.1.15 on 2026-02-02 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ['percent', 'fixed'])), name='valid_coupon_discount_type'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['Beginner', 'Intermediate', 'Advanced', 'All Levels', ''])), name='valid_course_level'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'archived'])), name='valid_course_status'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['video'])), name='valid_lecture_content_type'),
        ),
    ]
