# Generated by Django 5.1.15 on 2026-01-30 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureResource',
            fields=[
                ('resource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('document', 'Document'), ('code', 'Code'), ('other', 'Other')], default='other', max_length=20)),
                ('file_url', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'Lecture Resource',
                'verbose_name_plural': 'Lecture Resources',
                'db_table': 'lecture_resources',
                'ordering': ['lecture', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_url', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_content', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'PDF Content',
                'verbose_name_plural': 'PDF Content',
                'db_table': 'pdf_content',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.CharField(max_length=500)),
                ('video_provider', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('aws', 'AWS'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('video_quality', models.JSONField(blank=True, default=dict)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('captions_url', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'Video Content',
                'verbose_name_plural': 'Video Content',
                'db_table': 'video_content',
            },
        ),
    ]
