# Generated by Django 5.1.15 on 2026-02-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcontent',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='LectureResource',
        ),
        migrations.DeleteModel(
            name='PDFContent',
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
