# Generated by Django 5.2.10 on 2026-01-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_category_id_category_id_and_more'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfcontent',
            old_name='pdf_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='lectureresource',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='pdfcontent',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_content', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='courses.lecture'),
        ),
    ]
