# Generated by Django 5.2.10 on 2026-01-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_id_userprofile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='settings_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='skill_id',
            new_name='id',
        ),
    ]
