# Generated by Django 5.1.15 on 2026-02-03 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_add_course_check_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('class', 'Class Session'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('deadline', 'Deadline'), ('holiday', 'Holiday'), ('other', 'Other')], default='class', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Video conference or meeting link')),
                ('max_capacity', models.IntegerField(blank=True, help_text='Maximum participants allowed', null=True)),
                ('current_attendees', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('materials_url', models.URLField(blank=True, help_text='Link to course materials or resources')),
                ('recording_url', models.URLField(blank=True, help_text='Link to event recording')),
                ('notes', models.TextField(blank=True)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_before_hours', models.IntegerField(default=24, help_text='Hours before event to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events_created_by', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 'calendar_events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted')], default='registered', max_length=20)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Rating out of 5', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calendar_app.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Attendee',
                'verbose_name_plural': 'Event Attendees',
                'db_table': 'event_attendees',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_time', 'status'], name='calendar_ev_start_t_e41f01_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['instructor', 'start_time'], name='calendar_ev_instruc_d4a767_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['course', 'start_time'], name='calendar_ev_course__dcf61d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['event', 'attendance_status'], name='event_atten_event_i_e95d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['user', 'attendance_status'], name='event_atten_user_id_d971de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
    ]
