# Generated by Django 5.1.15 on 2026-02-02 10:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('courses', '0001_initial'),
        ('enrollments', '0002_add_unique_user_course_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('answer', models.JSONField(blank=True, default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Attempt',
                'verbose_name_plural': 'Question Attempts',
                'db_table': 'question_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='enrollment',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['assignment', 'order_index'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveConstraint(
            model_name='assignmentsubmission',
            name='valid_submission_status',
        ),
        migrations.RemoveConstraint(
            model_name='assignmentsubmission',
            name='valid_submission_score',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='valid_question_type',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='attachment_url',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded_by',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='show_correct_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice Question (Single Answer)'), ('msq', 'Multiple Select Question (Multiple Answers)')], default='mcq', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_type__in', ['quiz', 'assignment'])), name='valid_assignment_type'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_minutes__isnull', True), ('time_limit_minutes__gt', 0), _connector='OR'), name='valid_assignment_time_limit'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='valid_max_attempts'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('question_type__in', ['mcq', 'msq'])), name='valid_question_type'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.question'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('question', 'enrollment', 'attempt_number')},
        ),
    ]
