# Generated by Django 5.2.10 on 2026-01-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('courses', '0002_rename_category_id_category_id_and_more'),
        ('enrollments', '0002_rename_bookmark_id_bookmark_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='submission_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='attempt_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.quiz'),
        ),
    ]
