# Generated by Django 5.1.15 on 2026-02-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_update_assignments_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='content',
        ),
    ]
