# Generated by Django 5.1.15 on 2026-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_content_field'),
        ('enrollments', '0002_add_unique_user_course_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'graded', 'pending'])), name='valid_assignment_submission_status'),
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'submitted', 'graded'])), name='valid_question_attempt_status'),
        ),
    ]
